### ISSUE TITLE
Cannot PUT/PATCH image to a contact

### ISSUE THREAD

**Issue by under3415** [microsoftgraph/msgraph-sdk-dotnet-auth#103]
Using this HTTP in Postman to PUT a photo to a contact.
I get status 200 OK, but the photo is not visible for the contact.

````
PATCH /v1.0/me/contacts('XXXXXXXXXXXXX')/photo/$value HTTP/1.1
Host: graph.microsoft.com
Authorization: Bearer XXXXXXXXX
Content-Type: image/png
Content-Length: 22
````

I used 120x120 png image. I've set contact photo metadata (ProfilePhoto) to 

````
id = "120x120"
height = 120
width=120
````
 
[AB#8406](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8406)

**Comment by maisarissi** [comment]
Hi @under3415 

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
