### ISSUE TITLE
When it will be move to Live Version?

### ISSUE THREAD

**Issue by TejendraPrasad** [microsoftgraph/msgraph-sdk-dotnet-auth#108]
Hi Team,

When this library will be move to live version from preview so it can be used in production apps.

thank you!
Regards,
Tej 
[AB#9242](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9242)

**Comment by andrueastman** [comment]
Hey @TejendraPrasad.

We are not planning to move this out of preview. You can find more details about this at https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth/issues/63

The service library version supporting Azure.Identity is also available in preview, and you can find more details [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md#azure-identity).
