### ISSUE TITLE
Need To Support User Sign-out

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet-auth#12]
This is currently an [open issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/589) with MSAL and the only way to sign-out a user is to simply clear the cache for the user. Since we are abstracting MSAL, we need to provide developers some method that they can call to clear the token cache storage of the logged in user.

**Comment by darrelmiller** [comment]
I believe we are going  to need both a Login and a Logout method on the AuthorizationProviders.  They may need custom parameters per platform, so I don't think we need them to be part of any interface.  We should just try and make the naming consistent.

**Comment by peombwa** [comment]
No need for this since we expose `CreateClientApplication` that returns a client application.
