### ISSUE TITLE
Default callback for DeviceCodeProvider

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-auth#14]
Should we create a default implementation of the Device Code Flow provide call that writes to the Console?  Developers can provide their own callback if they want different behavior, but at least then it would work "out of the box". 
[AB#7205](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7205)

**Comment by darrelmiller** [comment]
Had another thought here.  Perhaps we can create a `dotnet new` template that will set this up and provide a default callback method.

**Comment by marcoscheel** [comment]
Is this solved? As of now I'm using the Microsoft.Graph.Auth Nuget and the device code provider is working.

https://www.nuget.org/packages/Microsoft.Graph.Auth

**Comment by maisarissi** [comment]
Hi @darrelmiller

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
