### ISSUE TITLE
Form resource url in client credential provider based on the applications national cloud

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet-auth#15]
[AB#7206](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7206)

**Comment by maisarissi** [comment]
Hi @peombwa 

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
