### ISSUE TITLE
Use new csproj format for test project

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-dotnet-auth#18]

**Comment by pwombwa** [comment]
@MIchaelMainer Also, going forward, all tests will use XUnit and not MSTest, correct?

**Comment by MIchaelMainer** [comment]
Correct.

**Comment by michael-hawker** [comment]
Looks like this was done already?  At least the new csproj format?  Can it be closed?

However, I did notice that when checking out the dev branch, the project wouldn't build as the test project used an older dependency version than the main project.  Updating it to match the main project worked fine though.
