### ISSUE TITLE
UserAssertion null in OBO provider

### ISSUE THREAD

**Issue by rjhaines** [microsoftgraph/msgraph-sdk-dotnet-auth#31]
I'm seeing a null UserAssertion parameter value on the first call to OnBehalfOfProvider.AuthenticateRequestAsync: 

![image](https://user-images.githubusercontent.com/28324940/55837159-5dd0a700-5ad5-11e9-89e9-642ad0a71904.png)

I'd appreciate any insights. Thanks!

**Comment by peombwa** [comment]
@rjhaines You need to call `.WithUserAssertion` passing a validated service token as a `UserAssertion`. Here is an example of how to do that.

```cs
// Create client application.
IConfidentialClientApplication clientApplication = OnBehalfOfProvider.CreateClientApplication(clientId, redirectUri, clientCredential);
OnBehalfOfProvider authenticationProvider = new OnBehalfOfProvider(clientApplication, scopes);

// Configure GraphServiceClient with provider.
GraphServiceClient graphServiceClient = new GraphServiceClient(authenticationProvider);

// Make a request with your user assertion
User me = await graphServiceClient.Me.Request().WithUserAssertion(new UserAssertion("validated_token")).GetAsync();
```
We will add documentation that explains how to use and extend our auth providers.

**Comment by rjhaines** [comment]
@pwombwa Thanks for your comment and proposed follow-ups.

In the meantime, can you provide a quick direction on acquiring the service token? So far I've tried `ConfidentialClientApplication.AcquireTokenForClientAsync` yet end up with an error: 
AADSTS50013: Assertion failed signature validation.

I'm currently using a client secret. Thanks for any further help you can provide.

**Comment by peombwa** [comment]
@rjhaines You can take a look at [this guide](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/on-behalf-of-2.x) from MSAL that explains how the OBO flow should be used. According to the guide, your client (web, desktop, mobile, single-page application) should call your service (API) as a user - use an auth flow that calls an API in the name of a user and not an app. `AcquireTokenForClientAsync` (Client Credential Flow) calls the API as an app and not a user.

You can call your service with either authorization code flow (web app) or interactice authentication (desktop and mobile). [This sample](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2/tree/cd/updateMSAL2.7.1/2.%20Web%20API%20now%20calls%20Microsoft%20Graph) by MSAL shows how to make a call from a desktop app to a service via interactive auth, then call Graph from the service via on behalf of flow.
