### ISSUE TITLE
The WithUsernamePassword extension should use SecureString as the type for the password parameter

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/msgraph-sdk-dotnet-auth#36]
The current signature enables worst practices for password storage. 

While I understand that the UsernamePassword provider is not recommended, if it is being used, then requiring a SecureString will force developers to "secure" the password before calling the SDK.

**Comment by peombwa** [comment]
@pschaeflein Thanks for reporting this. We will update **UsernamePasswordProvider** to use a SecureString as part of issue [#461](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/461).
