### ISSUE TITLE
Installation instructions incorrect

### ISSUE THREAD

**Issue by isthistechsupport** [microsoftgraph/msgraph-sdk-dotnet-auth#45]
The installation instructions for the Package Manager Console are incorrect: They currently say one must execute the command `Install-Package Microsoft.Graph.Auth` when the actual command ([taken from the NuGet webpage](https://www.nuget.org/packages/Microsoft.Graph.Auth)) is `Install-Package Microsoft.Graph.Auth -Version 1.0.0-preview.0`.

**Comment by peombwa** [comment]
Thanks for bringing this up. We will update the readme + our docs page to include `-PreRelease` option. i.e.
`Install-Package Microsoft.Graph.Auth -PreRelease`.
