### ISSUE TITLE
What are extraQueryParameters used for?  Can we raise the abstraction level?

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-auth#5]
https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth/blob/a209336f5243777ee58bf392e027a94a2191b795/Microsoft.Graph.Auth/Microsoft.Graph.Auth/PublicClient/DeviceCodeProvider.cs#L54

I would prefer to support only a subset of features of MSAL if we can significantly improve the usability.  Users can always call MSAL directly for edge cases.  So far the only thing I know extraQueryParameters are used for is adminConsent and now with the new checkbox on the consent dialog, our users are not likely to need this.

**Comment by pwombwa** [comment]
@darrelmiller removed in the latest commit
