### ISSUE TITLE
Reg:  Unable to find package 'Microsoft.Graph.Auth'

### ISSUE THREAD

**Issue by yChakradhar** [microsoftgraph/msgraph-sdk-dotnet-auth#52]
Hi Team,

When I try to install from NuGet package manager, getting the following error.
 Unable to find package 'Microsoft.Graph.Auth'
Please help me.

Regards,
Chakradhar

**Comment by peombwa** [comment]
The installation guide is missing a `-PreRelease`. You should install the package as such: `Install-Package Microsoft.Graph.Auth -PreRelease`. I'll update the readme to reflect the same. Thanks for bringing this to our attention.
