### ISSUE TITLE
IntegratedWindowsAuthenticationProvider on .NET Core

### ISSUE THREAD

**Issue by PhilPJL** [microsoftgraph/msgraph-sdk-dotnet-auth#56]
This code

```
var clientApplication = PublicClientApplicationBuilder
			.Create("<guid>")
			.WithTenantId("<guid>")
			.Build();
var authProvider = new IntegratedWindowsAuthenticationProvider(clientApplication);
var graphClient = new GraphServiceClient(authProvider);
```

works on .NET Framework, but fails on .NET Core with a PlatformNotSupportedException with message:

> AcquireTokenByIntegratedWindowsAuth is not supported on .net core without adding .WithUsername() because MSAL cannot determine the username (UPN) of the currently logged in user. Please use .WithUsername() before calling ExecuteAsync(). For more details see https://aka.ms/msal-net-iwa 

If I was using this directly:

`var result = await clientApplication.AcquireTokenByIntegratedWindowsAuth(scopes).ExecuteAsync();
`
I could add WithUsername("") to ge:

`var result = await clientApplication.AcquireTokenByIntegratedWindowsAuth(scopes).WithUsername("<username>").ExecuteAsync();
`

What's the solution when using the Auth library?

**Comment by peombwa** [comment]
Thanks for taking time to open this issue.

The Auth library has a `WithUserAccount(GraphUserAccount)` extension method that you can call on a request like this and set the users UPN to `GraphUserAccount.Email` property:

```cs
var clientApplication = PublicClientApplicationBuilder
    .Create("<guid>")
    .WithTenantId("<guid>")
    .Build();

var authProvider = new IntegratedWindowsAuthenticationProvider(clientApplication);

GraphServiceClient graphClient = new GraphServiceClient(authProvider);
var me = await graphClient.Me.Request()
    .WithUserAccount(new GraphUserAccount { Email = "UPN" }) // username (UPN) 
    .GetAsync();
```
