### ISSUE TITLE
Could not add Microsoft.Graph.Auth

### ISSUE THREAD

**Issue by jeffhee** [microsoftgraph/msgraph-sdk-dotnet-auth#59]
Hello,
I'm using a Core 3.1 project on MacOS, Visual Studio for Mac 8.5 Preview and attempting to add this package through nuget.

VS says "Could not add Microsoft.Graph.Auth" and provides the following in Package Console:

Getting restore information for project /Users/jeffhee/Documents/Projects/ms-graph-file-explorer/GraphTutorial/GraphTutorial.csproj
Running non-parallel restore.
Reading project file /Users/jeffhee/Documents/Projects/ms-graph-file-explorer/GraphTutorial/GraphTutorial.csproj.
Persisting no-op dg to /Users/jeffhee/Documents/Projects/ms-graph-file-explorer/GraphTutorial/obj/GraphTutorial.csproj.nuget.dgspec.json
Restoring packages for /Users/jeffhee/Documents/Projects/ms-graph-file-explorer/GraphTutorial/GraphTutorial.csproj...
Restoring packages for .NETCoreApp,Version=v3.1...
Resolving conflicts for .NETCoreApp,Version=v3.1...
Detected package downgrade: Microsoft.Identity.Client from 4.8.0 to 4.7.1. Reference the package directly from the project to select a different version. 
 GraphTutorial -> Microsoft.Graph.Auth 1.0.0-preview.3 -> Microsoft.Identity.Client (>= 4.8.0) 
 GraphTutorial -> Microsoft.Identity.Client (>= 4.7.1)
Checking compatibility of packages on .NETCoreApp,Version=v3.1.
Checking compatibility for GraphTutorial 1.0.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.Configuration.UserSecrets 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Graph 1.21.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Identity.Client 4.7.1 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Graph.Auth 1.0.0-preview.3 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.Configuration.Json 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Graph.Core 1.19.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for NETStandard.Library 1.6.1 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.CSharp 4.5.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.ComponentModel.TypeConverter 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Net.NameResolution 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Private.Uri 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.Serialization.Formatters 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.Serialization.Json 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.Serialization.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.SecureString 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Xml.XDocument 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Claims 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Principal 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.Configuration.FileExtensions 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.Configuration 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Newtonsoft.Json 9.0.1 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Net.Http 4.3.3 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.ValueTuple 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Diagnostics.DiagnosticSource 4.6.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Win32.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.AppContext 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Collections 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Collections.Concurrent 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Console 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Diagnostics.Debug 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Diagnostics.Tools 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Diagnostics.Tracing 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Globalization 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Globalization.Calendars 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.IO 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.IO.Compression 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.IO.Compression.ZipFile 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.IO.FileSystem 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.IO.FileSystem.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Linq 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Linq.Expressions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Net.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Net.Sockets 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.ObjectModel 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Extensions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Resources.ResourceManager 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.Extensions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.Handles 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.InteropServices 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.InteropServices.RuntimeInformation 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Runtime.Numerics 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.Algorithms 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.Encoding 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.X509Certificates 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Text.Encoding 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Text.Encoding.Extensions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Text.RegularExpressions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Threading 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Threading.Tasks 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Threading.Timer 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Xml.ReaderWriter 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Collections.NonGeneric 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Collections.Specialized 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.ComponentModel 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.ComponentModel.Primitives 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.TypeExtensions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.native.System 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Principal.Windows 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.1 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.NETCore.Targets 1.1.3 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Private.DataContractSerialization 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.FileProviders.Physical 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.Configuration.Abstractions 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Dynamic.Runtime 4.0.11 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.native.System.Net.Http 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Globalization.Extensions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.OpenSsl 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.native.System.IO.Compression 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Buffers 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Emit 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Emit.ILGeneration 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Reflection.Emit.Lightweight 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.native.System.Security.Cryptography.Apple 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.Cng 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Security.Cryptography.Csp 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Threading.Tasks.Extensions 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Xml.XmlDocument 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for System.Xml.XmlSerializer 4.3.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.FileProviders.Abstractions 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.FileSystemGlobbing 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for Microsoft.Extensions.Primitives 3.1.0 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.2 with .NETCoreApp,Version=v3.1.
Checking compatibility for runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0 with .NETCoreApp,Version=v3.1.
All packages and projects are compatible with .NETCoreApp,Version=v3.1.
Package restore failed. Rolling back package changes for 'GraphTutorial'.

Any ideas on how to fix this? I'd like to add this package so I can use the confidential client authentication.

Thank you!

**Comment by MIchaelMainer** [comment]
Are you still facing this issue? Can you update Microsoft.Identity.Client to 4.8.2 and let us know if that makes a difference?
