### ISSUE TITLE
Microsoft.Graph.Auth Release out of Preview

### ISSUE THREAD

**Issue by Tanzy** [microsoftgraph/msgraph-sdk-dotnet-auth#63]
Are there any plans on releasing the Microsoft.Graph.Auth NuGet package at anytime out of preview? General rule in our company is that we can't use preview packages in production code.

**Comment by darrelmiller** [comment]
Hi Tanzy,

We are not going to GA that library.  That was our plan, but we have changed our plan to adopt the Azure.Identity library which fulfils an identical function.  Moving to Azure.Identity will give developers a consistent experience between Graph SDKs and Azure SDKs.  

I talk more about this plan in the community call here:
https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-community-call-february-4-2020/

**Comment by csadam** [comment]
Does it mean that the Microsoft.Graph.Auth package is essentially deprecated and it is not recommended to use for new developments?  
If it is, then could you please add this status to the readme.md?

**Comment by Tanzy** [comment]
Could also mark the NuGet package as such and point to what should be used. Thinking about it updating samples would be good as well.

**Comment by christianarg** [comment]
Does this means that this doc are literally deprecated? https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=CS ??
