### ISSUE TITLE
Microsoft.Graph.Auth.  BadImageFormatException loading WorkerRole in Azure emulator

### ISSUE THREAD

**Issue by stefan2410** [microsoftgraph/msgraph-sdk-dotnet-auth#64]
Depedency on Microsoft.Graph.Auth last preview 4.
The solution was built normally but when I load the WorkerRole in Azure emulator, I get the following exception.

           System.BadImageFormatException: 'Could not load file or assembly 'Microsoft.Identity.Client, 
           Version=4.8.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies 
[AB#7209](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7209)

**Comment by maisarissi** [comment]
Hi @stefan2410 

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
