### ISSUE TITLE
Cannot get cache tokens of confidential client application according to the current ClientCredentialProvider implementation, 

### ISSUE THREAD

**Issue by asith-w** [microsoftgraph/msgraph-sdk-dotnet-auth#65]
As below implementation ,There are 5 tenants and need to retrieve graph users  of each tenants.  
because **ConfidentialClientApplication** is created with tenant id and app retrieves graph users again for same tenants  ,it generates another new token instead of using cache token  
is there ClientCredentialProvider implementation to solve this issue ?

[below code in gist](https://gist.github.com/asith-w/c3166b7018363d94cf7807ae880b2319)
```
public async Task ExecuteAsync( )
 {  

var tenantIds = new List<string>{
	 "1448f51b-234d-123345-86c8-0f6a634bbbb1",
	 "2448f51b-234d-123345-86c8-0f6a634bbbb2",
	 "3448f51b-234d-123345-86c8-0f6a634bbbb3",
	  "4448f51b-234d-123345-86c8-0f6a634bbbb4",
	  "5448f51b-234d-123345-86c8-0f6a634bbbb5"
};  

IConfidentialClientApplication confidentialClientApplication;
//1st requests
foreach (var tenantId in tenantIds)
{
	confidentialClientApplication = ConfidentialClientApplicationBuilder
									.Create(_azureADConfiguration.ClientId)
									.WithTenantId(tenantId)
									.WithClientSecret(_azureADConfiguration.ClientSecret)
									.Build();

	var clientCredentialProvider = new ClientCredentialProvider(confidentialClientApplication);
	var graphServiceClient = new GraphServiceClient(clientCredentialProvider);
	var users = await graphServiceClient.Users
										.Request()
										.GetAsync();


}
//2st requests
foreach (var tenantId in tenantIds)
{
				
	confidentialClientApplication = ConfidentialClientApplicationBuilder
										.Create(_azureADConfiguration.ClientId)
										.WithTenantId(tenantId)
										.WithClientSecret(_azureADConfiguration.ClientSecret)
										.Build();

	var clientCredentialProvider = new ClientCredentialProvider(confidentialClientApplication);
	var graphServiceClient = new GraphServiceClient(clientCredentialProvider);
	var users = await graphServiceClient.Users
										.Request()
										.GetAsync();
//two tokens are generated for each tenant.
}
``` 
[AB#7210](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7210)

**Comment by MIchaelMainer** [comment]
A ClientCredentialProvider instance is intended to authenticate per single tenant. We recommend that you create a dictionary of GraphServiceClient instances by tenant ID, and reuse those GraphServiceClient instances across your application. Don't re-instantiate GraphServiceClient per tenant.

**Comment by asith-w** [comment]
will  dictionary of GraphServiceClient instances manage cache tokens ? following way is managed cache tokens properly
[https://stackoverflow.com/questions/61802091/how-to-handle-appcachetokens-of-multi-tenant-daemon-service-application-using-ms](https://stackoverflow.com/questions/61802091/how-to-handle-appcachetokens-of-multi-tenant-daemon-service-application-using-ms/61803512#61803512)

**Comment by MIchaelMainer** [comment]
Got it. MSAL provides a mechanism to manage tokens for different tenants with the same client instance (and cache) which would have allowed a single GraphServiceClient to work across all tenants. We didn't expose [WithAuthority](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/442227e1899ba45511840cbb1f59cfbd571b1546/src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs#L230) (or it wasn't available when we did the work).

At this point, you'll have to have one client per tenant and allow each client + its MSAL manage token cache. 

For us, we should verify that having x-tenant tokens managed in a shared token cache is what we want. If so, then the next auth integration+iteration should expose WithAuthority.

cc: @darrelmiller

**Comment by maisarissi** [comment]
Hi @asith-w 

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
