### ISSUE TITLE
Web App sample using OnBehalfOf provider

### ISSUE THREAD

**Issue by TiagoBrenck** [microsoftgraph/msgraph-sdk-dotnet-auth#67]
Hello,

Is there any web app sample using OnBehalfOf provider, that leverages MSAL external token cache provider (ie InMemory)?

Thanks 
[AB#7211](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7211)

**Comment by maisarissi** [comment]
Hi @TiagoBrenck 

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
