### ISSUE TITLE
Getting Build Error: Unable to parse version value '1.0.0-preview.5' from 'packages.config After Adding Microsoft.Graph.Auth

### ISSUE THREAD

**Issue by shwork96** [microsoftgraph/msgraph-sdk-dotnet-auth#76]
I'm adding some code to access Graph to an ASP.net MVC project. When I add the latest Microsoft.Graph.Auth package from Nuget I get the following error when I build:

Error Unable to parse version value '1.0.0-preview.5' from 'packages.config'.

 

The other graph libraries work fine. I've used the auth package just fine in another mvc core project. I'm using VS 2019 Enterprise.

**Comment by MIchaelMainer** [comment]
Please try upgrading to  a Nuget.exe version to greater than 4.3. Answered from https://stackoverflow.com/questions/58804537/visual-studio-2019-unable-to-parse-version-value-1-0-0-preview2-from-packages, please up vote if it helps.

**Comment by gallettoNL** [comment]
I have the same issue.
I don't have a Nuget.exe on my system, it's incorporated in VS2019 (latest version), I believe, so why does this error occur, an how to solve it?
