### ISSUE TITLE
can you add support for Microsoft Bookings

### ISSUE THREAD

**Issue by rheophile10** [microsoftgraph/msgraph-sdk-dotnet-auth#78]
Would you? 

https://docs.microsoft.com/en-us/graph/api/resources/booking-api-overview?view=graph-rest-beta

The only other reference I see is 

https://github.com/microsoft/bookings-samples

**Comment by MIchaelMainer** [comment]
This exists in the Microsoft.Graph.Beta package. 

```csharp
var result = await graphClient.BookingBusinesses.Request().GetAsync();
```
