### ISSUE TITLE
Get Planner Plans trough Graph Api from Azure Function

### ISSUE THREAD

**Issue by mgordic** [microsoftgraph/msgraph-sdk-dotnet-auth#79]
Hi,

Is there any example how I can achieve following requirement:

I need to read Planner Plans from Group in an Azure Function trough Graph Api. 

Application permissions are not supported, only delegated.

I tried with ConfidentialClientApplicationBuilder with OnBehalfOfProvider, but no luck. I do not know how to set UserAssertion in this case.

 
[AB#7213](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7213)

**Comment by MIchaelMainer** [comment]
Please see https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/460 for an example of how you can do this.

**Comment by MIchaelMainer** [comment]
Please reopen if there is a bug associated with this issue.
