### ISSUE TITLE
Code: generalException Message: An error occurred sending the request.

### ISSUE THREAD

**Issue by ghanshyambb** [microsoftgraph/msgraph-sdk-dotnet-auth#85]
Inner Exception: Code: authenticationChallengeRequired
Message: Authentication challange is required.

`IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
.Create(clientId).
WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")
.WithClientSecret(clientSecret)
.WithAuthority("https://login.microsoftonline.com/organizations/")
.Build();

string[] scope = new string[] {"Directory.AccessAsUser.All", "Directory.Read.All","Directory.ReadWrite.All" };

AuthorizationCodeProvider authProvider = new AuthorizationCodeProvider(confidentialClientApplication,scope);
GraphServiceClient graphClient = new GraphServiceClient(authProvider);
**var directory = await graphClient.Directory.Request().GetAsync();**
`

get directory give generalexception dont know what i am doing wrong any help for this? 
[AB#7215](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7215)

**Comment by MIchaelMainer** [comment]
You'll need to describe your scenario in more detail. Who are the actors? What is the nature of this application?

**Comment by ghanshyambb** [comment]
@MIchaelMainer i have created api application to get information of azure resources with all its property. i have registered my app in azure portal under active directory through which i will get all the resource information by different sdk 
now i want to get information of Active directory using graph sdk. i have use above code for authentication for active directory detail under my subscription.

**Comment by maisarissi** [comment]
Hi @ghanshyambb 

Thank you for reaching out and opening this issue. This client library will not leave the preview state. Microsoft.Graph v4 now integrates with Azure.Identity which supports a wide variety of authentication flows out of the box.
We suggest that you migrate to v4 + Azure.Identity. Read more about it in this [issue](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935).



This issue won't be fixed, and the repository will be archived.
