### ISSUE TITLE
Microsoft.Graph.Auth 1.0.0-preview.5 - Production Code

### ISSUE THREAD

**Issue by vijayaram-b** [microsoftgraph/msgraph-sdk-dotnet-auth#86]
We are planning to use the Graph API to read the emails from the Azure Directory. Our company policy state that we should only use published packages not pre-release or preview packages. Could someone advise when this package will be officially published, if not is there any alternative for the same.

**Comment by MIchaelMainer** [comment]
This package won't become an official release. We now plan on aligning the auth client story for the Microsoft Graph clients to work with TokenCredential provided by Azure.Identity. It is the mechansim by which the Azure SDKs get authorization. In the meantime, I'd suggest that you implement your own implementation of IAuthenticationProvider that directly uses MSAL.
