### ISSUE TITLE
We don't need to accept ResourceUrl as a parameter because it is always the same for Graph

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-dotnet-auth#9]
https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth/blob/a209336f5243777ee58bf392e027a94a2191b795/Microsoft.Graph.Auth/Microsoft.Graph.Auth/ConfidentialClient/ClientCredentialProvider.cs#L47

**Comment by pwombwa** [comment]
@darrelmiller fixed in the latest commit
