### ISSUE TITLE
When will there be a released auth-package?

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/msgraph-sdk-dotnet-auth#94]
Hi there,
We were waiting on the release of this package. 
Today I have found the issue #63 Microsoft.Graph.Auth Release out of Preview. 
So this package will never been released.
Is there a roadmap, when Azure.Identity library will be integrated?

**Comment by ddyett** [comment]
No there are no plans to release this package.  Azure Identity work is currently being completed but you can try out the integration in the preview version. I'm hoping to have this much closer to release in January.

https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.0-preview.3

**Comment by pschaeflein** [comment]
@ddyett - what branch/fork/tag is the preview built from? Didn't see an obvious answer...
