### ISSUE TITLE
 How to get OAuth access token from VSTO Outlook add-in when user logged to Office 365

### ISSUE THREAD

**Issue by albertly** [microsoftgraph/msgraph-sdk-dotnet-auth#98]
My end user has Outlook connected to Office 365 and have an old VSTO add-in that needs to connect to  my Rest API.

I need to implement SSO solution to my Rest API.

I want to get an access token  from VSTO add-in without prompting an user (or maybe prompting once ), he is already authenticated in Outlook with his Office 365 account.

Is it possible? 
[AB#8002](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8002)

**Comment by MIchaelMainer** [comment]
@albertly I don't know if this is possible. This repo is for the Microsoft Graph .NET authentication library for use with the .NET client libraries for Microsoft Graph. This would be an excellent question to post to StackOverflow.
